### ISSUE TITLE
Feature Request: Quick Settings Tile

### ISSUE THREAD

**Issue by DeanWinchesterrr** [F0x1d/DNS-Manager#1]
Reference: 
https://github.com/joshuawolfsohn/Private-DNS-Quick-Tile

App works amazingly well, a qs tile would be much appreciated. Thank you for everything you do.

**Comment by F0x1d** [comment]
Could you explain what Quick Tile should do? Switch to next DNS server in list or switch DNS mode?

**Comment by DeanWinchesterrr** [comment]
> Could you explain what Quick Tile should do? Switch to next DNS server in list or switch DNS mode?

That can always be a option in your app, 

"QS tile Mode : Toggle or Switch"

In case you don't wanna do the extra work, then the next priority would be to have the qs tile as switch DNS mode. Cause if someone wants to change the DNS Provider they could just open the App, not a big problem. But having the ability to switch DNS mode right from the QS tile would be pretty cool.

**Comment by F0x1d** [comment]
Done in v1.0.2

**Comment by DeanWinchesterrr** [comment]
> Done in v1.0.2

Wow that was so quick. Thanks a lot !!

**Comment by TvT2080** [comment]
> Done in v1.0.2

I'm using this app. And I have some idea for improvements:

1. Could you please change **the title** of the qs tile from "**Switch Modes**" to "**Private DNS**" 

2. Could you also change the function, by this I mean you switch from existing **DNS Hostname** to "**Auto**" mode. Could you perhaps change "**Auto mode**" to **OFF**? 

3. Could you add another tile that switch to other hostnames? I'm sure the app can have two tiles right? One to switch modes **ON - OFF** and one to switch **hostnames**.

I know it's easier said than done. But I would really appreciate if you could make these changes. Thank you for reading.

**Comment by F0x1d** [comment]
Done in v1.0.3

**Comment by Wahid7852** [comment]
> Done in v1.0.3

Hey greetings developer, really impressed by your work on this. 

I have a small request , can you Please remove Auto Mode from Qs Tile it's annoying. 🥲

OFF - ON = Much Better. Auto is useless.

Also under Private DNS qs tile can you remove "custom" and put the name of the DNS that we set while creating DNS profile in the app? 

For example I put Adguard as name when creating DNS profile in app, I want that name in the qs time under PrivateDNS much better. Thanks a lot man, keep doing what you do.

**Comment by DeannWinchesterr** [comment]
![-214756_temp](https://github.com/F0x1d/DNS-Manager/assets/131953486/8bc0b6cc-b637-4961-ae02-299591c43690)
Can you change this icon please ?

> Done in v1.0.3

**Comment by F0x1d** [comment]
To which one?

**Comment by DeannWinchesterr** [comment]
> To which one?

https://pictogrammers.com/library/mdi/icon/dns/

**Comment by F0x1d** [comment]
But this one is used in the second tile

**Comment by DeannWinchesterr** [comment]
> But this one is used in the second tile

I think this is used in second tile

https://pictogrammers.com/library/mdi/icon/dns-outline/

**Comment by DeannWinchesterr** [comment]
> > Done in v1.0.3
> Also under Private DNS qs tile can you remove "custom" and put the name of the DNS that we set while creating DNS profile in the app?

Also this is a good idea

**Comment by F0x1d** [comment]
This is just outline version of the same icon, it will be confusing for people to have 2 tiles with practically the same icons

The first tile should have icon which indicates something about changeable mode (ON-OFF state)

**Comment by DeannWinchesterr** [comment]
> This is just outline version of the same icon, it will be confusing for people to have 2 tiles with practically the same icons
> 
> The first tile should have icon which indicates something about changeable mode (ON-OFF state)

https://pictogrammers.com/library/mdi/icon/switch/

What about this ?

**Comment by F0x1d** [comment]
I don't think switch is really connected with ON-OFF state

**Comment by F0x1d** [comment]
Done in v1.0.4

**Comment by DeannWinchesterr** [comment]
> Done in v1.0.4

I like the New icon. The app is complete now. Thank you

**Comment by TvT2080** [comment]
> Done in v1.0.4

Thank you for your great job
